<?php

namespace A2C\PlatformBundle\Repository;

/**
 * ContactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannedAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
